universe = vanilla
executable = submit_condor.sh
arguments = $(IOV) $(VERSION) $(MAXFILES)

transfer_input_files = make, src, interface, input_files, CondFormats, PileUp, JetMETCorrections, files
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = rootfiles

output = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)/log_$(IOV)_$(VERSION).out
error  = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)/log_$(IOV)_$(VERSION).err
log    = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)/log_$(IOV)_$(VERSION).log

request_memory = 4000MB
request_disk = 300MB
request_cpus = 1

+JobFlavour = "workday"

queue
