universe = vanilla
executable = submit_PostProcessing_condor.sh
arguments = $(IOV) $(VERSION)

transfer_input_files = rootfiles/$(VERSION), post_processing.py, addAllIOVs.py, histogram_scripts, input_files
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = $(VERSION)
transfer_output_remaps = "$(VERSION) = rootfiles/$(VERSION)"

output = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)_PostProcessing/log_$(IOV)_$(VERSION).out
error  = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)_PostProcessing/log_$(IOV)_$(VERSION).err
log    = /afs/cern.ch/work/j/jessy/private/CMS/PNET_Regression/Residuals/logs_L2L3Res/dijet_logs/$(VERSION)_PostProcessing/log_$(IOV)_$(VERSION).log

request_memory = 4000MB
request_disk = 800MB
request_cpus = 1

+JobFlavour = "tomorrow"

queue
